if(SANITIZER)
  if(SANITIZER STREQUAL "Address")
    message(STATUS "Building with AddressSanitizer")
    string(APPEND CMAKE_CXX_FLAGS " -fsanitize=address -fno-omit-frame-pointer")
  elseif(SANITIZER STREQUAL "Thread")
    message(STATUS "Building with ThreadSanitizer")
    string(APPEND CMAKE_CXX_FLAGS " -fsanitize=thread")
  elseif(SANITIZER STREQUAL "Undefined")
    message(STATUS "Building with UndefinedSanitizer")
    string(APPEND CMAKE_CXX_FLAGS " -fsanitize=undefined")
  else()
    message(STATUS ${SANITIZER})
    message(FATAL_ERROR "The Sanitizer is not supported")
  endif()
endif()
